{{- if not .Values.objstore.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: logging-objstore
  namespace: {{ include "loki.namespace" . }}
type: Opaque
data: {{ .Values.objstore.data | b64enc }}
{{- end }}
